#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:01:00 
#SBATCH -J nblock_job 
#SBATCH -o NBlockedOutputFile.%j.out
#SBATCH -e NBlockedErrorFile.%j.err

srun -n 1 -N 1 --cpu-freq=2400000 ./benchmark-nblocked
