#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:01:00 
#SBATCH -J TMBlocked_job 
#SBATCH -o TMBlockedOutputFile.%j.out
#SBATCH -e TMBlockedErrorFile.%j.err


srun -n 1 -N 1 --cpu-freq=2400000 ./benchmark-tmultblocked
